### ISSUE TITLE
RuntimeError  256 model for multi prompts

### ISSUE THREAD

**Issue by junwenxiong** [arthur-qiu/LongerCrafter#11]
It seems that the cross-attention calculation under the multi prompts is problematic.
![image](https://github.com/arthur-qiu/LongerCrafter/assets/35716657/eca22be8-a9ef-482c-a7ae-52a747357b4c)

**Comment by arthur-qiu** [comment]
Are you using [run_text2video_freenoise_mp_256.sh](https://github.com/arthur-qiu/LongerCrafter/blob/main/scripts/run_text2video_freenoise_mp_256.sh)?

**Comment by junwenxiong** [comment]
YES

**Comment by o0o0o00o0** [comment]
> It seems that the cross-attention calculation under the multi prompts is problematic. ![image](https://private-user-images.githubusercontent.com/35716657/291061956-eca22be8-a9ef-482c-a7ae-52a747357b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDA0NDIsIm5iZiI6MTczMTA0MDE0MiwicGF0aCI6Ii8zNTcxNjY1Ny8yOTEwNjE5NTYtZWNhMjJiZTgtYTllZi00ODJjLWE3YWUtNTJhNzQ3MzU3YjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA0MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWY0MGFjMWI1MTQyMDE3ZTc1YzM1YjZkMjVhYzYwOTMwYTcyYzAwYjU1MTM2Nzc4ZTc5Y2QxYTk3ZjM5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zmnMKD5ccoiCrBmDc6y7L_O83b_CG7ZsO1oVIVopg-4)

I also encountered this problem, how should I solve it?
