### ISSUE TITLE
Evaluation Mechanism

### ISSUE THREAD

**Issue by zhuolingli** [arthur-qiu/LongerCrafter#19]
Thank you for your great work! 

Could you kindly share the prompts used for testing or evaluation? I’m not very familiar with this field, so I was wondering if there is a commonly used test set for evaluation?

**Comment by arthur-qiu** [comment]
You can use https://github.com/evalcrafter/EvalCrafter/blob/master/prompt700.txt. But there is no commonly used test set for evaluation now.

**Comment by zhuolingli** [comment]
It’s very helpful. Many thanks!

**Comment by arthur-qiu** [comment]
We use 512 prompts from https://evalcrafter.github.io/. But they updated the prompt file and now have 700 prompts.
