### ISSUE TITLE
Image2Video

### ISSUE THREAD

**Issue by wandrzej** [arthur-qiu/LongerCrafter#2]
Thank you for releasing the code and paper. 

In the readme you show image to video results, but only text2video scripts are shared. Is this something that will require additional work to release?

**Comment by arthur-qiu** [comment]
FreeNoise currently only supports the text2video task and I do not show any image2video results. For i2v task, you are invited to see https://arxiv.org/abs/2310.12190 and https://github.com/AILab-CVC/VideoCrafter. We will continue to upgrade it.

**Comment by arthur-qiu** [comment]
Sorry, the old version exactly has a typo and I have fixed it.
