### ISSUE TITLE
project website code

### ISSUE THREAD

**Issue by JianliWei1995** [arthur-qiu/LongerCrafter#4]
Hi Qiu,

Congrats to your amazing work! Your project website is very well-organized and attractive. Would you like to share a template for making that website?

Thanks,

**Comment by arthur-qiu** [comment]
Feel free to refer https://github.com/arthur-qiu/arthur-qiu.github.io/tree/master/projects.

**Comment by JianliWei1995** [comment]
Thank you Haonan. By the way, your resume (http://haonanqiu.com/cv/) on your personal website looks very well-organized and clean. If you are using Latex, would like to share the template in any chance?

**Comment by arthur-qiu** [comment]
https://www.latextemplates.com/template/medium-length-professional-cv

**Comment by JianliWei1995** [comment]
Appreciate your sharing with me!
