### ISSUE TITLE
First model link 404

### ISSUE THREAD

**Issue by SoftologyPro** [arthur-qiu/LongerCrafter#5]
https://huggingface.co/VideoCrafter/Text2Video-512-v1/blob/main/model.ckpt

**Comment by arthur-qiu** [comment]
We find VideoCrafter remove this ckpt and I am checking with them. Currently, you can use other models instead.

**Comment by SoftologyPro** [comment]
Can you host the model on your huggingface?  It is needed for good 512x512 results?

**Comment by arthur-qiu** [comment]
Sorry, I was asked to remove this ckpt. They will release it again within one month.

**Comment by arthur-qiu** [comment]
> Can you host the model on your huggingface? It is needed for good 512x512 results?

It will be back today.

**Comment by SoftologyPro** [comment]
Link still 404

**Comment by arthur-qiu** [comment]
> Link still 404

Are you using the old link? It works for me. (https://huggingface.co/MoonQiu/LongerCrafter/blob/main/model_512.ckpt)

**Comment by SoftologyPro** [comment]
Thanks.  Yes, I was using the link in my original post.  Downloads fine now.
